spring.application.name=BookService

server.port = 9090

spring.datasource.url = JDBC:mysql://localhost:3306/Online_Bookstore_BookDetails
spring.datasource.driver-class-name = com.mysql.jdbc.Driver
spring.jpa.database = MYSQL

spring.datasource.username = root
spring.datasource.password = Yash@0404

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true

BOOK_FOUND=Particular book detail fetched successfully
BOOK_NOT_FOUND=No Book Found
BOOK_ALREADY_THERE=Book is already there
BOOK_ADDED=Book has been added successfully
BOOK_MODIFIED=Book has been modified successfully
BOOK_DELETED=Book has been deleted successfully

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/admin
management.endpoint.prometheus.enabled=true